---
# tasks file for ansible-role-letsencrypt

- name: Include variables and set facts
  ansible.builtin.include_tasks: facts.yml
  tags: siteurl, profile

- name: Install Let's Encrypt dependent packages
  ansible.builtin.package:
    name: "{{ certbot_packages }}"
    state: present
  when:
    - certbot_packages is defined
    - certbot_packages | length > 0
    - use_letsencrypt is defined
    - use_letsencrypt

- name: Use Let's Encrypt if specified
  ansible.builtin.include_tasks: "letsencrypt.yml"
  when:
    - use_letsencrypt is defined
    - use_letsencrypt
  tags: siteurl, profile
