name: Ansible-Role-LetsEncrypt CI Testing

on: 
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
    branches: [ master ]

jobs: 
  test:
    runs-on: self-hosted
    strategy:
      fail-fast: false
      matrix:
        molecule_distro:
          - "centos:7"
          - "centos:8"
          - "debian:10"
          - "debian:11"
          - "ubuntu:18.04"
          - "ubuntu:20.04"
    steps:
      - uses: actions/checkout@v2
      - name: Setup Python3
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - name: Pip install Repo Requirements
        run: pip install -r requirements.txt
      - name: Molecule Test
        run: molecule test
        env:
          MOLECULE_IMAGE: ${{ matrix.molecule_distro }}
